version: '3'

services:    
  mysql:
    image: mysql:latest
    container_name: api_mysql
    restart: always
    env_file:
      - .env
    ports:
      - '${DB_PORT}:3306'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    volumes:
      - ./__data/mysql/:/var/lib/mysql/
    networks:
      - ljy_admin_net

  redis:
    image: redis:alpine
    container_name: api_redis
    restart: always
    env_file:
      - .env
    ports:
      - '${REDIS_PORT}:6379'
    command: >
      --requirepass ${REDIS_PASSWORD}
    networks:
      - ljy_admin_net

  ljy-admin-server:
    image: ljy-admin-server:latest
    container_name: api_server
    ports:
      - "7001:7001"
    volumes:
      - ./logs/:${PROJECT_DIR}/logs/
    restart: always
    networks:
      - ljy_admin_net
    depends_on:
      - mysql
      - redis
    command: ["sh", "-c", "wait-for-it mysql:3306 -- wait-for-it redis:6379 -- npm run start"]  # 使用wait-for-it等待MySQL和Redis启动

networks:
  ljy_admin_net:
    name: ljy_admin_net
