services:
  ljy-admin-web:
    # 从当前路径构建镜像
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    image: ljy-admin-web:latest
    ports:
      - '80:80'
    env_file:
      - .env
      - .env.production
